
os: osx
language: node_js
node_js:
  - 8

install:
  - npm install -g electron-osx-sign
  - sh add-osx-key.sh
  - curl -f -o jamovi.zip https://downloads.jamovi.org/travis-builds/jamovi-unsigned.zip
  - unzip -q jamovi.zip
  - rm jamovi.zip
  
script:
  - sh sign.sh
