
os: osx
osx_image: xcode11.3
language: node_js
node_js:
  - 8

env:
  HOMEBREW_NO_AUTO_UPDATE: 1

install:
  - npm install -g electron-osx-sign
  - brew install marcelomazza/homebrew-curl-libssh2/curl
  
  - sh add-osx-key.sh
  - curl -f -o jamovi.zip https://www.jamovi.org/downloads/jamovi-unsigned.zip
  - unzip -q jamovi.zip
  - export VERSION=`cat jamovi.app/Contents/Resources/jamovi/version`
  - rm jamovi.zip
  
script:
  - sh sign.sh
  - ditto -c -k --sequesterRsrc --keepParent jamovi.app jamovi.zip
  - sh notarize-app.sh jon@thon.cc ${APP_SPECIFIC_PASSWORD} org.jamovi.jamovi jamovi.app jamovi.zip
  - rm jamovi.zip
  - ditto -c -k --sequesterRsrc --keepParent jamovi.app jamovi.zip
  
  - mkdir bundle
  - mv jamovi.app bundle
  - ln -s /Applications bundle/Applications
  - hdiutil create -size 1000m tmp.dmg -ov -volname "jamovi" -fs HFS+ -srcfolder bundle
  - hdiutil convert tmp.dmg -format UDZO -o jamovi.dmg
  - rm -f tmp.dmg

after_success:
  - echo "${SFTP_KEY}" | base64 --decode >/tmp/sftp_rsa

  - /usr/local/opt/curl/bin/curl
         -f
         --ftp-create-dirs
         --insecure
         --key /tmp/sftp_rsa
         -T jamovi.dmg
         sftp://${SFTP_USER}@jamovi.org/home/${SFTP_USER}/jamovi.org/downloads/jamovi-$VERSION-macos.dmg

  - /usr/local/opt/curl/bin/curl
         -f
         --ftp-create-dirs
         --insecure
         --key /tmp/sftp_rsa
         -T jamovi.zip
         sftp://${SFTP_USER}@jamovi.org/home/${SFTP_USER}/jamovi.org/downloads/jamovi-$VERSION-macos.zip

