
os: osx
osx_image: xcode11.3
language: node_js
node_js:
  - 8

env:
  HOMEBREW_NO_AUTO_UPDATE: 1

install:
  - npm install -g electron-osx-sign
  - brew install marcelomazza/homebrew-curl-libssh2/curl
  
  - sh add-osx-key.sh
  - curl -f -o jamovi.zip https://downloads.jamovi.org/travis-builds/jamovi-unsigned.zip
  - unzip -q jamovi.zip
  - export VERSION=`cat jamovi.app/Contents/Resources/jamovi/version`
  - rm jamovi.zip
  
script:
  - sh sign.sh
  - ditto -c -k --sequesterRsrc --keepParent jamovi.app jamovi.zip
  - sh notarize-app.sh jon@thon.cc ${APP_SPECIFIC_PASSWORD} org.jamovi.jamovi jamovi.app jamovi.zip
  - rm jamovi.zip
  - hdiutil create -size 1000m tmp.dmg -ov -volname "jamovi" -fs HFS+ -srcfolder .
  - hdiutil convert tmp.dmg -format UDZO -o jamovi.dmg
  - rm -f tmp.dmg

after_success:
  - /usr/local/opt/curl/bin/curl
         --ftp-create-dirs
         --insecure
         -T jamovi.dmg
         sftp://${SFTP_USER}:${SFTP_PASSWORD}@downloads.jamovi.org/home/${SFTP_USER}/downloads.jamovi.org/travis-builds/jamovi-$VERSION-macos.dmg
